### ISSUE TITLE
Protoc & macOS Catalina

### ISSUE THREAD

**Issue by Volcore** [android/tuningfork#1]
When using macOS Catalina, I'm getting the following error:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/95790/90952256-66274900-e462-11ea-9f79-5e725710f52a.png">

I was able to resolve it by running Cmd + Clicking the package. But this is something that everyone on our team has to do now when building for the first time.

Is it necessary to include the protoc compiler? We usually pre-build our protocol buffers files, maybe that's possible here as well (and only include the built files, but not the protoc compiler).

**Comment by ktaraymovich** [comment]
Yes, it is necessary to include protoc as plugin regenerates protocol buffer files depends on the settings you are using. I've added additional message about it the UI.

**Comment by cgydev** [comment]
Getting this issue on MacMini with Big Sur,
I am not sure what button to press to make sure the plugin functions correctly. Any suggestion ?

**Comment by cgydev** [comment]
Am getting the same Box on MacMini with Big Sur. Since I have pressed cancel, it is showing the following note in the Tuner window.

![Screenshot 2021-07-20 at 12 50 41 PM](https://user-images.githubusercontent.com/6255441/126278909-e4e36d98-d994-4d66-996d-519214ee9737.png)

Any information as to how to move from here ?

**Comment by ktaraymovich** [comment]
If you still seeing this message - open protoc binary location in _Finder_ -> right click -> choose _Open_ -> it should show the dialog again.

**Comment by biralpucar** [comment]
Days I get these bugs. All google searches yielded no results. Please help me.





![Screenshot_1](https://github.com/android/tuningfork/assets/62028194/a9d721d8-62b4-45bb-a4ec-b45ae3040a15)

**Comment by ifraud** [comment]
@biralpucar Could you share the contents of your dev_tuningfork.proto? It sounds like the file got corrupted with unrecognized characters. Have you tried to just compile it separately to see if you encounter the same issue?

**Comment by biralpucar** [comment]
@ifraud yes, I change it as in the image and compile it again, I remove the package and install it again, but the result is always the same..

![fail](https://github.com/android/tuningfork/assets/62028194/3f82454b-3bc3-416a-b849-79639ac47de9)
![Screenshot_1](https://github.com/android/tuningfork/assets/62028194/d5310244-adcf-48b4-a63e-e627305c53ee)
