### ISSUE TITLE
Always response code: 400 and no telemetry update

### ISSUE THREAD

**Issue by DziD** [android/tuningfork#10]
Android Performance Tuner integrated, I got success message about initialisation apt

<img width="980" alt="Screenshot 2021-08-13 at 00 20 42" src="https://user-images.githubusercontent.com/710049/129272724-08422c3f-cc8a-4535-a2bc-ceecef3882b5.png">

But next I always have that

<img width="1682" alt="Screenshot 2021-08-13 at 00 33 22" src="https://user-images.githubusercontent.com/710049/129273310-6e9c9b5e-fc4b-48ee-8d29-ff8605f105ac.png">

I check api key, and it correct. What do I wrong?

I use custom annotations, no custom fidelity
Android 11, unity 2019.4.23, backend mono (on il2cpp the same problem, doesn't matter development or not)

@ktaraymovich @Lothav can you help me?

**Comment by eristella** [comment]
Hello @paradizIscool, are you still experiencing this issue?
If yes, could you try downloading the latest APT release? 
We have fixed a bug in the authentication with the API key that might solve your problem.
Cheers!

**Comment by paradizIscool** [comment]
Hi @eristella,
Thanks for the update, unfortunately it does not change my issue.
I certainly miss something on my side, but I have to work on something else, I will come back on it as soon as possible.

{
	"error": {
		"code": 400,
		"message": "API key not valid. Please pass a valid API key.",
		"status": "INVALID_ARGUMENT",
		"details": [{
			"@type": "type.googleapis.com/google.rpc.ErrorInfo",
			"reason": "API_KEY_INVALID",
			"domain": "googleapis.com",
			"metadata": {
				"service": "performanceparameters.googleapis.com"
			}
		}]
	}
}

**Comment by eristella** [comment]
Should you still experience the issue in the future, please do not hesitate to post some logs so we may be of assistance!
Remember to remove your personal info from the logs :)

Cheers!

**Comment by paradizIscool** [comment]
@eristella 
Hi back to the task

```
I/TuningFork: TuningFork Settings:
      method: 1
      interval: 30000
      n_ikeys: 4
      n_annotations: 1
      n_histograms: 4
      base_uri: https://performanceparameters.googleapis.com/v1/
      api_key: PERSONNAL APIKEYREMOVED
      fp filename: dev_tuningfork_fidelityparams_1.bin
      itimeout: 1000
      utimeout: 100000
    Settings::Histograms
    ikey: 64000 min: 6.540000 max: 60.000000 nbkts: 200
    ikey: 64001 min: 10.000000 max: 40.000000 nbkts: 30
    ikey: 64003 min: 0.000000 max: 20.000000 nbkts: 30
    ikey: 64002 min: 0.000000 max: 20.000000 nbkts: 30
    
    
I/TuningFork:Web: Connecting to: https://performanceparameters.googleapis.com/v1/applications/PACKAGENAME/apks/20208:uploadTelemetry
D/UnityAds: com.unity3d.services.core.webview.WebViewApp.invokeJavascriptMethod() (line:131) :: Invoking javascript: javascript:window.nativebridge.handleEvent(["LIFECYCLE","PAUSED","com.google.firebase.MessagingUnityPlayerActivity"]);
I/TuningFork:Web: Response code: 400
    Response message: Bad Request
W/TuningFork:Web: java.io.FileNotFoundException:
 https://performanceparameters.googleapis.com/v1/applications/PACAKGENAME/apks/20208:uploadTelemetry
W/TuningFork.GE: Error 15 when sending UPLOAD request
```

![Capture d’écran 2022-02-17 à 11 22 27](https://user-images.githubusercontent.com/11227595/154456510-085fd3b4-9a1b-4b24-a512-ce0bca7a3eab.png)

Tried with and without restriction, google project is good, API key is good, the package name is good. I don't know what else to do.
Unity 2020.3.27

**Comment by eristella** [comment]
Hi @paradizIscool, could you check whether you have the permissions for INTERNET and ACCESS_NETWORK_STATE in your AndroidManifest?
