### ISSUE TITLE
Android Performance Tuner causes instant crash on emulators (Bluestacks/Nox)

### ISSUE THREAD

**Issue by Lightboom9** [android/tuningfork#13]
As specified in the title, tuner causes instant (even before unity logo can be shown if it's enabled) crash. Not blackscreen, app just instantly closes. The problem is also not in the Optimized Frame Pacing, as the app crashes without it enabled just as well. On actual Android device, tuner works as intended - or does nothing if used. Even if tuner is not actually used in code in any way, it still crashes the app on emulators, it won't work if you add it to the project.

Is there a way to fix this or a workaround? Because there is no way to distinguish between emulator and actual android device.

**Comment by EricaStella93** [comment]
Hi @Lightboom9, thanks for the report.
Would it be possible to have the log with the error that makes the app crash?

Thanks!

**Comment by ifraud** [comment]
Closing as no further update on this.
