### ISSUE TITLE
Linked docs outdated/confusing (LoadingState annotation)

### ISSUE THREAD

**Issue by smt923** [android/tuningfork#14]
I don't really know where best to report this but I keep running into small issues like trying to setup my scene loading so I of course follow the docs and read this section: https://developer.android.com/games/sdk/performance-tuner/unity/define-parameters#annotations

I read through and it says to look for `LoadingState` in my annotation and even explains how to set the loading state when loading a new scene below, so it's very confusing to me that I don't have this...

Upon some googling I come across the code here and see it's appears to be actually deprecated: https://github.com/android/tuningfork/blob/1d56b845325114a0ff2d20be37fef970fd37d467/Editor/Scripts/Names.cs#L35

The docs even say they were last updated in July so I think most people would assume they're pretty up to date and not everyone will look through code to find out more, it's a small little thing but a lot of this stuff is complicated for people's first time so I figured I should post an issue about it anyway

Also, there's this set of [codelab tutorials](https://developer.android.com/codelabs/android-performance-tuner-unity#0) I keep coming across which often ranks higher than the main docs, often very close but out of sync even with the main docs, which is another confusing point, I did give feedback on the docs pages but I can't really give context or information to that feedback

**Comment by eristella** [comment]
Hi @smt923, thanks for the report!
We're in the process of updating all our docs, everything should be in order soon! :) 
Should you find any other problems, please let us know!

Cheers!
