### ISSUE TITLE
"Could not open proc/0/" error logs show up when trying to initialize APT on Android device and data not being sent

### ISSUE THREAD

**Issue by nathan-mag** [android/tuningfork#16]
Hi all - I have an issue when trying to run the APT on device. As the title says, the APT seems to initialize OK and can connect with the Google services, but I get error codes relating to something called "proc". I thought it may be to do with the "protoc" executables included in the package (which don't run on Mac because of security but can be white-listed) but I've allowed them to run and still it happens.

Here is a screenshot of my logcat when starting the game;

<img width="1281" alt="Screenshot 2022-03-09 at 15 03 06" src="https://user-images.githubusercontent.com/71647590/157473674-41eac9bc-ee9c-42e7-b342-1143c1678026.png">

I have seen a [similar issue](https://github.com/android/tuningfork/issues/15) on here and have tried all suggested fixes but with no luck. Please can someone help? On my Google Cloud Platform dashboard, I see some requests for the 'Android Performance Parameters API', but the 'error' percentage is 100%.

I am using Android Performance Tuner v1.5.0 (2022-02-10) and I'm on Unity 2019.4.32 LTS.

Edit: after initialization, every submission interval, I am getting this log (first line is the red error);

`2022-03-09 16:11:49.243 9598-11565/com.--- E/memtrack: Couldn't load memtrack module`

`2022-03-09 16:11:49.243 9598-11565/com.--- W/android.os.Debug: failed to get memory consumption info: -1`

`2022-03-09 16:11:49.835 9598-11563/com.--- I/TuningFork:Web: Connecting to: https://performanceparameters.googleapis.com/v1/applications/com.---/apks/65:uploadTelemetry`

`2022-03-09 16:11:49.838 9598-11563/com.--- I/System.out: (HTTPLog)-Static: isSBSettingEnabled false`

`2022-03-09 16:11:49.839 9598-11563/com.--- I/System.out: (HTTPLog)-Static: isSBSettingEnabled false`

`2022-03-09 16:11:50.035 9598-11563/com.--- I/TuningFork:Web: Response code: 403`

`2022-03-09 16:11:50.035 9598-11563/com.--- I/TuningFork:Web: Response message: Forbidden`

`2022-03-09 16:11:50.035 9598-11563/com.--- W/TuningFork:Web: java.io.FileNotFoundException: https://performanceparameters.googleapis.com/v1/applications/com.---/apks/65:uploadTelemetry`

```
2022-03-09 16:11:50.035 9598-11563/com.--- W/TuningFork.GE: Error 15 when sending UPLOAD request
    {"name": "applications/com.---/apks/65", "session_context": {"device": {"brand": "samsung", "build_version": "29", "cpu_core_freqs_hz": [2002000000, 2002000000, 2002000000, 2002000000, 2504000000, 2504000000, 2730000000, 2730000000], "device": "x1s", "fingerprint": "samsung/x1sxeea/x1s:10/QP1A.190711.020/G981BXXS4BTHH:user/release-keys", "gles_version": {"major": 3, "minor": 2}, "model": "SM-G981B", "product": "x1sxeea", "soc_manufacturer": "", "soc_model": "", "swap_total_bytes": 2684350464, "total_memory_bytes": 11412451328}, "game_sdk_info": {"session_id": "ec29a2c6-1465-4ddd-8f71-3ecf5e12f146", 
 "swappy_version": "1.3.0", "version": "1.5.0"}, "time_period": {"end_time": "2022-03-09T16:11:49.269268Z", "start_time": "2022-03-09T16:11:19.323218Z"}}, "telemetry": [{"context": {"annotations": "CAE=", "duration": "29.946050632s", "tuning_parameters": {"experiment_id": "", "serialized_fidelity_parameters": ""}}, "report": {"battery": {"battery_event": [{"app_o
```

Thanks.

**Comment by eristella** [comment]
Hi @nathan-mag, thanks for the report!
We're currently working on fixing the errors about `/proc/0/oom_score` and `/proc/0/status`. As of the moment, unfortunately, the memory metrics won't contain those information but the rest of APT is unaffected.
On the other hand, `Error 15 when sending UPLOAD request` is usually due to missing permissions in your android manifest. Could you double check you have the INTERNET and ACCESS_NETWORK_STATE permissions?
Thanks!

**Comment by nathan-mag** [comment]
Hey @eristella, thank you so much for your quick reply and information regarding the /proc issue.
I have double checked my manifest and pasted it below, I have those 2 permissions at the bottom of the manifest;

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.---" android:versionCode="1" android:versionName="1.0">
  <application android:extractNativeLibs="true" android:label="@string/app_name" android:icon="@mipmap/app_icon">
    <!-- The MessagingUnityPlayerActivity is a class that extends
         UnityPlayerActivity to work around a known issue when receiving
         notification data payloads in the background. -->
    <activity android:name="com.google.firebase.MessagingUnityPlayerActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    <service android:name="com.google.firebase.messaging.MessageForwardingService" android:exported="false" />
    <receiver android:name="com.adjust.sdk.AdjustReferrerReceiver" android:permission="android.permission.INSTALL_PACKAGES" android:exported="true">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
    </receiver>
    <activity android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    <activity android:name="com.facebook.unity.FBUnityDialogsActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    <activity android:name="com.facebook.unity.FBUnityGamingServicesFriendFinderActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    [...]
  </application>
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
</manifest>
```

Can you see anything incorrect or suggest something else that may be causing this issue? 
Thank you.

**Comment by eristella** [comment]
It might be an API key problem. Could you check its correctness following the procedure specified [here](https://developer.android.com/games/sdk/performance-tuner/unity/troubleshooting) for response code 403?
