### ISSUE TITLE
Unity debug log spam

### ISSUE THREAD

**Issue by toxikman** [android/tuningfork#18]
Found in version 1.5.0:

Line 62 of CProtobufSerialization.cs
`Debug.LogFormat("DeallocCallbackImpl.size: {0}", parameters.size);`

Please comment out this unnecessary log or add a debug verbosity setting.

**Comment by eristella** [comment]
Thanks for the report!
Will do in the next release :)

Cheers!

**Comment by toxikman** [comment]
Thank you!  While you're looking at that, you might also consider whether this other frequent logging is necessary for app developers like us to be seeing:

```
Android Performance Tuner Initializer
Android Performance Tuner RefreshAssetsCompleted
```
Again maybe adding a "Verbose Debug Log" option in the APT settings would be desirable for certain people?

**Comment by toxikman** [comment]
Hi, it's been a few months, so we're just wondering what the status of the next release is?  Our engineers and designers continue to question me about this log spam. it's rather bothersome to the team and because we're using APT as a package, it isn't easy to remove the spam by editing the APT source ourselves. Thanks!

**Comment by amjaliks** [comment]
A vote from me. `DeallocCallbackImpl.size` messages only pollutes a logout output.
Thanks!

**Comment by toxikman** [comment]
Thank you so much @eristella and it's so kind and thorough of you to follow up here!
