### ISSUE TITLE
AOT Compiler Confusion

### ISSUE THREAD

**Issue by toxikman** [android/tuningfork#19]
The documentation contains [this section regarding Unity's AOT compiler](https://developer.android.com/games/sdk/performance-tuner/unity/initialize-library#aot-compile). It implies that if you're using IL2CPP you'll need to include the code mentioned.

1. It's confusing about whether other versions of Unity like 2020-2022 require this as well.
2. It's confusing why this isn't just automatically generated in the `Assets/AndroidPerformanceTuniner_gen` folder? In the APT package scripts, you know what version of Unity you're running and what enums are in `DevTuningFork.cs` (since this file is also auto-generated).
3. During testing on Android (under Unity 2020.3.32 with IL2CPP), we did not include the recommended `ForceReflectionInitialization` code. There was no indication of a problem and the histograms showed up in the TuningFork testing app. But we're still not seeing data in the Google Play Console. Perhaps we need to publish the app first before it will appear in the Console?  Or is `ForceReflectionInitialization` needed for Unity 2020 as well?
4. The documentation lists `LoadingState` as an enum, but this is no longer available and has been replaced with its own system which uses `LoadingTimeMetadata.LoadingState` and `LoadingTimeMetadata.LoadingSource`. Do we need to use `ForceReflectionInitialization` on those two enums or others?

**Comment by eristella** [comment]
Hi, @toxikman,
Thanks for the feedback! 
Let me answer your questions by number:
1. Unity versions 2020-2022 don’t require it. 
2. We will try and add the automatic generation in the next releases :) 
3. To see data in the Play console the app must be published and a minimum quantity of data must be available for privacy reasons. You can publish your app on an Internal Testing track for testing purposes. ForceReflectionInitialization is not connected with Play console.
4. No, you don’t have to include those two enums or others. We are trying to replace the deprecated LoadingState annotation in our docs but apparently we’ve missed some places :)

Hope this helps,
Cheers!

**Comment by toxikman** [comment]
This is a great help, thanks for your kindness and quick answers. Everything is cleared up now.

**Comment by eristella** [comment]
Could you leave the comments on the docs here?
I'll try to go through them asap :)

**Comment by toxikman** [comment]
Nothing I didn't already mention above regarding the [AOT compiler section](https://developer.android.com/games/sdk/performance-tuner/unity/initialize-library#aot-compile).  I would just make it clearer that the section only applies to Unity 2019 and prior versions (the previous grammar was a bit ambiguous). Also update the code for the LoadingState changes.

**Comment by eristella** [comment]
Thanks for the feedback!
I'm closing this issue but feel free to reopen it should you need any further info :)
Cheers!
