### ISSUE TITLE
Keeping the settings consistent with other Google Products

### ISSUE THREAD

**Issue by Volcore** [android/tuningfork#2]
Hi,

it would be great if this library would keep the settings consistent with other Google libraries.

We now have:

- A top level menu item called "Google" (which is a no-no to me)
- A Window -> Google item which only has the "Game Package Registry"
- A Window -> Firebase menu item
- A Window -> Google Play Games menu item
- An Assets -> Google Mobile Ads menu item

It would be really great if this was kept consistent. I personally would prefer if all Google things would live under "Window -> Google -> <thing>".

<img width="512" alt="image" src="https://user-images.githubusercontent.com/95790/90952355-43496480-e463-11ea-80f7-50647099a031.png">

**Comment by zfdave** [comment]
Offer u ort !!!
We have too many menu items be added on the top level....google, facebook, adjust, aws ....

A small  config file (or const.cs) can brings me joy: 
`MenuItem("Assets/" + const_path + "Google/xxxx")`
