### ISSUE TITLE
Terminal popups during Unity compile

### ISSUE THREAD

**Issue by FodderMK** [android/tuningfork#22]
Whenever Unity compiles (such as re-importing scripts) I see two windows pop up and quickly disappear.  This is being caused by the processes spun up via `ProtocCompiler.CreateDescriptor` and `ProtocCompiler.CompileProto` methods.  It could also have something to do with my system using the new Windows Terminal app as the default.  It's not breaking anything but I do find it distracting.  Could `CreateNoWindow=true` be added to the `ProcessStartInfo` settings to prevent these windows?

Somewhat related, the log messages `Android Performance Tuner SceneListChanged` and `Android Performance Tuner RefreshAssetsCompleted` are a bit excessive.  Could they be disabled?

Edit: Another alternative would be detecting if these ProtocCompiler calls even need to be made.  If nothing related to PerformanceTuning has changed then it's likely the calls can be skipped

**Comment by eristella** [comment]
Hi @FodderMK, thank you for your feedback!
I'll investigate the windows popping up and insert the fix in the next release.
We're also adding an option to avoid the log messages you mentioned, so please bear with us a little longer :)

Cheers!

**Comment by eristella** [comment]
Hello!
Please have a look at the latest release for fixes to the opening window and disabling the logs :)

**Comment by FodderMK** [comment]
Looks good, thank you!
