### ISSUE TITLE
I am getting protoc compiler error in the package I imported

### ISSUE THREAD

**Issue by msedeveloper** [android/tuningfork#25]
![picone](https://user-images.githubusercontent.com/108843537/183620707-df9f83a0-dafd-4884-a8bf-5fe34d163be0.PNG)

![pictwo](https://user-images.githubusercontent.com/108843537/183620826-0b6096ff-d456-4045-a85e-14f8ba5f6846.PNG)

![picthree](https://user-images.githubusercontent.com/108843537/183620882-aac8fac3-f1f3-44f6-9d1c-a1dd4451d4c2.PNG)

![picfour](https://user-images.githubusercontent.com/108843537/183620935-bf87bf6e-233f-40b0-8f44-3644be0d2205.PNG)

![picfive](https://user-images.githubusercontent.com/108843537/183620975-69ce2da6-7f36-4b5a-9162-03aa0c59020c.PNG)

![picsix](https://user-images.githubusercontent.com/108843537/183621097-99d0b55c-5f71-4244-8f50-2ed00276b9c0.PNG)

![pictwelve](https://user-images.githubusercontent.com/108843537/183621025-8450e6e3-a915-468b-a0ad-4bd66c3d4dd0.PNG)

![picseven](https://user-images.githubusercontent.com/108843537/183621145-258b59c7-f148-4300-8b04-d2df66e6bbcb.PNG)

![piceight](https://user-images.githubusercontent.com/108843537/183621232-ffd8b803-be95-4909-8b96-d1a49b282a50.PNG)

![picnine](https://user-images.githubusercontent.com/108843537/183621275-b222325d-f76b-4e81-b4e9-88b6d1af0da6.PNG)

![picten](https://user-images.githubusercontent.com/108843537/183621302-6217eec6-4b50-4744-806f-5d88db95ffdc.PNG)

![piceleven](https://user-images.githubusercontent.com/108843537/183621372-6e197edd-b7c7-4d0c-8a2e-8634efb944e1.PNG)

![pictwelve](https://user-images.githubusercontent.com/108843537/183621464-85c0abf4-1011-4469-af74-1be9692b20d0.PNG)

is there something i didn't add i couldn't solve the problem in any way i am not a professional developer please help?
unity version 2020.3.3
unity version 2021.3.8
unity version 2019.4.4
have the same error
c sharp version 2022,2019
framework version 4.7.1, 4.6

**Comment by eristella** [comment]
Hi!
It looks like there are some non-ascii characters in your dev_tuningfork.proto file.
Are you perhaps using non-ascii characters for scene names, annotations or fidelity parameters?
[This](https://www.w3schools.com/charsets/ref_html_ascii.asp) is a list of accepted characters.
I'll be happy to help you look for the character that's causing the problem if you could paste here your dev_tuningfork.proto file.

**Comment by msedeveloper** [comment]
hello actually this project is new i haven't done any coding yet i didn't use non ascii characters

no matter what project i open i get the same error
Thanks for your help

[dev_tuningfork.zip](https://github.com/android/tuningfork/files/9309348/dev_tuningfork.zip)

**Comment by msedeveloper** [comment]
@eristella  I solved the problem, thank you very much for your help
