### ISSUE TITLE
Version 1.5.1 removes all scripting define symbols and it only leaves ANDROID_PERFORMANCE_TUNER_UTILITIES when applied

### ISSUE THREAD

**Issue by rpuigc** [android/tuningfork#27]
we`ve some scripting define symbols in Unity, when we imported the plugin, it overrides the scripting define symbols list, leaving only the one that the plugin needs. 

i`ve corrected this issue by changing (Assets/AndroidPerformanceTuner/Editor/Scripts/Initializer.cs at line 168):

 `PlayerSettings.SetScriptingDefineSymbolsForGroup(
                EditorUserBuildSettings.selectedBuildTargetGroup,
                Paths.utilitiesScriptingSymbol);`

For:

`string definesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(EditorUserBuildSettings.selectedBuildTargetGroup);
            System.Collections.Generic.List<string> allDefines =  new List<string>(definesString.Split(';'));

            if (!allDefines.Contains(Paths.utilitiesScriptingSymbol))
                allDefines.Add(Paths.utilitiesScriptingSymbol);

            PlayerSettings.SetScriptingDefineSymbolsForGroup(
                EditorUserBuildSettings.selectedBuildTargetGroup,
                string.Join(";", allDefines.ToArray()));`

**Comment by eristella** [comment]
Hi @rpuigc,
Thanks for the report!
We'll insert the fix in the next release :)

Cheers!

**Comment by toxikman** [comment]
This is a really serious bug that's messing things up for us too. Could your team please rush a patch release package 1.5.2 with just this fix? Thank you.

**Comment by toxikman** [comment]
Hi @eristella, is there a patch coming to fix this?

**Comment by eristella** [comment]
Hi @toxikman and @rpuigc,
we removed the scripting define symbol and moved the Utilities scripts in the Samples~ folder.
Instructions on how to import them are in the release notes :)

Hope this works for you,
Cheers!
