### ISSUE TITLE
v1.5.1: LoadingSceneTracker is not recognized by Unity (UPM)

### ISSUE THREAD

**Issue by YuukiARIA** [android/tuningfork#28]
LoadingSceneTracker.cs and LoadingSceneTrackerEditor.cs are not recognized to be compiled because they are outside of asmdef.
When installing as UPM, scripts inside the package must be associated to asmdef.
https://docs.unity3d.com/Manual/cus-asmdef.html

**Comment by eristella** [comment]
Hi @YuukiARIA,
Thanks for the report!
We'll insert the fix in the next release :)

Cheers!

**Comment by eristella** [comment]
Hi @YuukiARIA,
could you also confirm what Unity Editor version you're using?

Thanks!

**Comment by YuukiARIA** [comment]
@eristella 
Thanks for replying.
I'm using Unity 2020.3.34f1.

**Comment by eristella** [comment]
Hi @YuukiARIA,
we moved the LoadingSceneTracker in the Samples~ folder in the latest release :)
You can import it from the Package Manager.

Hope this solution works for you,
Cheers!
