### ISSUE TITLE
Assemblydef missing in AndroidPerformanceTuner_gen

### ISSUE THREAD

**Issue by Volcore** [android/tuningfork#3]
When trying to follow the tutorial [here](https://developer.android.com/games/sdk/performance-tuner/unity/initialize-library), one issue is that FidelityParams and Annotation classes are generated into the "AndroidPerformancetuner_gen" folder. That folder doesn't have an asmdef, so it can't be easily included.

It can be fixed by manually creating a .asmdef file and adding the protobuf dependecy to it, but that's an extra step that's not mentioned in the tutorial and requires some digging into it.

**Comment by ktaraymovich** [comment]
.asmdef is automatically created now with other generated files.
