### ISSUE TITLE
Unexpectedly large frame times in the stats

### ISSUE THREAD

**Issue by Razenpok** [android/tuningfork#35]
I've added the APT to my game, and the stats that I see in the Play Console are very confusing, as I don't see any FPS drops during testing on a wide range of devices.
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/8434406/216139935-51236ee1-33e8-4bb7-b05b-7a2728024289.png">

I think that might be because I use OnDemandRendering in my game to halt the rendering during times of player inactivity completely. Do you think this might be the case for such a strange statistic in the Console?

Reference:
https://blog.unity.com/technology/how-on-demand-rendering-can-improve-mobile-performance

**Comment by Inspyro** [comment]
I can confirm that this is happening. We tried to use On-Demand Rendering to render at 15FPS while updating the UI at 60FPS which resulted in a very smooth gameplay experience but leads to the "wrong" reporting.

This is especially concerning as Google now plans to punish apps that cannot achieve 20FPS consistently.
See: https://android-developers.googleblog.com/2023/03/GGDS-recap-blog.html

Unfortunately games that don't need 30FPS updates are not considered with this new metric that was introduced to Android Vitals.

**Comment by ifraud** [comment]
Currently we don't intend for the new Per-device Bad Behaviour Thresholds to apply to On-Demand Rendering games. Could you tell us the names of your titles that use On-Demand Rendering so that we can confirm that they are on our exclusion list?

**Comment by Razenpok** [comment]
[Happy Color®: Coloring Book](https://play.google.com/store/apps/details?id=com.pixel.art.coloring.color.number)

**Comment by ifraud** [comment]
@Razenpok Your game was detected automatically internally and was added to the exclusion list.  At the moment, there is no official way to go about the exclusion list, but that is being worked on atm.
