### ISSUE TITLE
Performance Tuner is crashing Unity on old (but "supported") devices

### ISSUE THREAD

**Issue by bilck** [android/tuningfork#4]
Our app is crashing at least on Galaxy Tab E (SM-T560) on initialization due to Android Performance Tuner SDK (v1.0.0).
I have attached the log leading to the crash to this issue.

[Android Performance Tuner Crash Log.txt](https://github.com/android/tuningfork/files/5263980/Android.Performance.Tuner.Crash.Log.txt)

**Comment by bilck** [comment]
Is anyone responsible for this repository?
There are a few issue posts with no answers...

**Comment by ktaraymovich** [comment]
Hi, 

Thanks for your bug report.
Could you please specify your settings, it will help identify the issue.

- OS: [e.g. macOS, Windows]
- Unity Version  [e.g. 2019.3.4f1]
- Project Settings -> Other Settings
  - Graphics API
  - Scripting Runtime Version 
  - Scripting Backend 
  - Api Compatibility Level 
  - Target Architectures
  - Split APKs by target architecture
  - Strip Engine Code / Managed Stripping Level
- Project Settings -> Resolution and Presentation (for > 2019.3)
  - Optimized Frame Pacing
- Publishing Settings 
  - Split Application Binary
- Build Settings
  - Build System
  - Export Project
  - Build App Bundle
  - Development Build

**Comment by bilck** [comment]
- **OS: Android 4.4.4 and 4.4.2.**
- **Devices: Samsung Galaxy Tab E and Samsung Galaxy Tab Pro 8.4**
- Unity 2019.4.8f1 (it also happens on at least 2019.4.10f1)
- Project Settings:
    - Graphics API: Auto Graphics API
    - Scripting Runtime Version: .NET Standard 2.0 
    - Scripting Backend: IL2CPP
    - API Compatibility Level: 19
    - Target Architectures: ARMv7, ARM64
    - Split APKs by target architecture: false
    - Strip Engine Code: true / Low
- Optimized Frame Pacing: true
- Split Application Binary: false
- Build Settings:
    - Build System: gradle
    - Export project: no
    - Build App Bundle: yes
    - Development build: it crashes on both development and release builds.

We have a few crash reports on Firebase which might be related to that but unfortunately, it's not that easy to share.

**Comment by bilck** [comment]
A quick update on this issue:

- What causes the crash is not Android Performance tuner plugin _per se_, but the `Optimized Frame Pacing` flag on Unity's PlayerSettings.

I don't know if I should close this issue or not, but this is something that I believe should be talked over with Unity representatives.

**Comment by tim-pp** [comment]
is there any chance you can open a bug reporter and link the report number here?

**Comment by eristella** [comment]
Hello, I'm closing this issue as Swappy will be updated soon :)
