### ISSUE TITLE
Multiple Issues / Questions with tuningfork.

### ISSUE THREAD

**Issue by mariusJanke** [android/tuningfork#40]
Hey there,

I'm integrating TuningFork (Android Performance Tuner) into my Unity-based mobile game. However, I've encountered a few issues and need some guidance:

1. The TuningFork log mentions a "large number of annotation combinations" and suggests adjusting Settings.max_num_metrics.frame_time. I'm only using 2 enums with a total of 24 entries, but I'm unsure how to modify this setting. Could you provide instructions on changing this?

2. On the second game start, I'm getting the error log "Error ticking 64000 : 32" every frame. Any insights on what this error means and how to debug it?

3. Regarding the recommended "Aggregation Strategy" of "Time Based" with 10 minutes, we observe session times between 2-5 minutes for our players. How does this 10-minute calculation work? Does it accumulate over multiple sessions? Does TuningFork send the collected data on application close, or is it lost? Would setting a shorter time like 2 minutes be more suitable for our usage?

Thanks for your help!

**Comment by labalov** [comment]
Hello,

1. annotation combinations basically mean the number of different combinations your enums could take. For example if you have 2 enums with 12 entries each, then your annotation combinations would be 12*12 = 144. The maximum annotations that can be recorded in a single session is 64. 

2. This is directly limited to the annotation combinations. If you exceed the maximum number of annotations; some data might end up not being recorded. Reducing your annotation combinations to below 64 should prevent such messages from appearing.

3. If your sessions are 2-5 minutes; I suggest keeping the aggregation interval to 2 minutes. TuningFork does send the data on application close but it would still be safer to keep aggregation interval shorter if your sessions don't reach 10 minutes.
