### ISSUE TITLE
Can it be added into the GooglePlayPlugins

### ISSUE THREAD

**Issue by zfdave** [android/tuningfork#5]
Maybe add it into the [Google Registry for Unity](https://developer.android.com/games/develop/build-in-unity#open-package-manager) is a good idea, This makes it more kindly for develoers.

Just like them [GooglePlayPlugins](https://github.com/google/play-unity-plugins/tree/master/GooglePlayPlugins)

**Comment by ktaraymovich** [comment]
Thank you for your feedback!

At the moment we don't have plans of changing way of distribution, so we will continue with the current github repo for now.
