### ISSUE TITLE
Let us use Scriptable Objects for enum configuration + Addressable Scenes Support

### ISSUE THREAD

**Issue by bilck** [android/tuningfork#7]
Currently "Android Performance Tuner for Unity" auto-generate enums and save them in the Tuning Fork class.

This is especially problematic for scene list generation.
We use addressables/bundles to download scenes from the Internet, which by default are NOT listed on the build settings scenes and thus, not included in the auto-generated enum and not discoverable by the default annotations mechanism.

We had to create a mechanism to include **and disable** Addressable scenes in our BuildSettings, so that it is included on the code generated enum. Besides that, we also parsed the scene path from the "OnSceneLoaded" event to an enum value.

I believe these kind of mechanisms are nice inclusions to the built-in plugin code.

Also: the plugin would be better integrated with Unity if we could create enums by using Scriptable Objects, which then could be auto-detected by the plugin codegen process OR passed as a parameter in some way.

**Comment by ktaraymovich** [comment]
Thank you for your feedback!

Few questions to clarify your setup:
1. Are you using default or custom annotation? 
2. Did you try using custom annotation + creating new enum for your scenes instead of auto-generated enum for scenes?

**Comment by bilck** [comment]
1. Custom Annotation
2. We have considered it, but we also consider this approach very error-prone.

I have just considered another option for this that solves this issue for most people: it should be possible to annotate a static method that returns a list/array of Scene Paths or a `Dictionary<string, int>`. That way you can append to the list any scenes that your build process includes, and even "dynamically built" scenes.
This could apply to other enums as well, think about a [TuningForkProvider(string key)] annotation for methods that returns the required values for code generation.

**Comment by eliatlas** [comment]
Voting for this. We have an issue with levels annotations. If the game has 500 levels for example, we need to add 500 enum values manually.

**Comment by bilck** [comment]
> Thank you for your feedback!
> 
> Few questions to clarify your setup:
> 
> 1. Are you using default or custom annotation?
> 2. Did you try using custom annotation + creating new enum for your scenes instead of auto-generated enum for scenes?

1. Custom annotation
2. That wouldn't work for us at all. Besides the manual work, it is too error-prone.

**Comment by oddgames-david** [comment]
I would much prefer a long or guid to identify the level, we have a custom level editor coming soon and it'd be useful to know if a specific level generated by users is causing the frame drops

**Comment by ktaraymovich** [comment]
Thank you for your feedback! At the moment there is only support for enums in Annotation.
About generated code for _scenes_- you don't have to use it and can exclude it from your Annotation if you are defining custom Annotation.

**Comment by timbo-tj** [comment]
Our game supports scenes being added after launch. We simply upload an updated set of asset bundles, and bam, new level added to the game.

But this library requires us to define our level names before hand and ship it with the binary?

We really need a way to feed a string value into the annotations so it can support dynamic scenes.

**Comment by timbo-tj** [comment]
Will this be considered at some point?

**Comment by eristella** [comment]
Hello!
The latest APT release introduces support for Addressables scenes :)
Thank you for your patience and please let us know your feedback!

Cheers!

**Comment by timbo-tj** [comment]
Oh awesome stuff, great to see the package is still being improved and developed! I'll let you all know how we go on our end.
