### ISSUE TITLE
Scene enum wont be built and throws exceptions trying to convert

### ISSUE THREAD

**Issue by kevinsquid** [android/tuningfork#9]
07-28 07:52:25.336: E/Unity(4859): SetCurrentAnnotation({ }) result is InvalidAnnotation

Will be thrown as  MessageUtil.SetScene(annotation, to.buildIndex) fails.

Unity build uses asset bundles, streaming assets or other methods that do not build the scene into the application. Such methods will result in the buildIndex returning -1 which is normal.

the scene name should be used instead.

- Also, The scene enums to be registered must be added to the Build Settings in unity.

**Comment by kevinsquid** [comment]
I managed to make progress by removing the unity package and downloading the repo to fix MessageUtil.SetScene() to  use the name of the scene path then converting that into an enum which worked but the set annotation methods still throws invalid enum from within the compiled .so library.

I suspect these problems are arising as we use AssetBundles instead of packing everything into a singular App.

I ended up removing this from our project for simplicity.

**Comment by eristella** [comment]
Hello, unfortunately APT only supports scenes inserted in the Build Settings at build time at the moment.
Is your scene in the Build Settings at build time?

**Comment by eristella** [comment]
Hello!
Not sure if this fits your use case with AssetBundles, but the latest APT release introduces support for scenes in Addressables :)
I'm closing this issue but feel free to reopen it should you have any more questions and please let us know your feedback!

Cheers!
